### PR TITLE
Use FIFO timer ordering in FakeAsync

### PR DESCRIPTION
**Pull request by alechenninger**
Migrated from https://github.com/google/quiver-dart/pull/265

I had to copy over fake_async_test.dart entirely since it wasn't in this repo.

Thanks!

### CODE REVIEW

**Comment by alechenninger** [comment]
I noticed there are some things missing in this fork from the original quiver-dart library. Would you like me to add back [this change](https://github.com/google/quiver-dart/commit/ed05b5c56e632ff6061ae451d7fef7b03cf1f30f)?

**Comment by alechenninger** [comment]
Somewhat unrelated, but I noticed when copying over the missing test that this commit might be missing too: https://github.com/google/quiver-dart/commit/671f1bc75742b4393e203c9520a3bf1e031967dc

**Comment by yjbanov** [comment]
Uh oh! Good find! Please, if you could add these back, would be awesome!

**Comment by yjbanov** [comment]
Let's pull the missing commit in a separate PR

**Pull request merged**
